// <auto-generated />
using System;
using BookEcommerceWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookEcommerceWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112161908_AddproductTable")]
    partial class AddproductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookEcommerceWeb.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9020),
                            DisplayOrder = 1,
                            Name = "Hành động",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9021)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9025),
                            DisplayOrder = 2,
                            Name = "Khoa học viễn tưởng",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9026)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9027),
                            DisplayOrder = 3,
                            Name = "Lịch sử",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9028)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9029),
                            DisplayOrder = 4,
                            Name = "Ngôn tình",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9031),
                            DisplayOrder = 5,
                            Name = "Trinh thám",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 19, 8, 706, DateTimeKind.Utc).AddTicks(9032)
                        });
                });

            modelBuilder.Entity("BookEcommerceWeb.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BookEcommerceWeb.Models.Models.Product", b =>
                {
                    b.HasOne("BookEcommerceWeb.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
