// <auto-generated />
using System;
using BookEcommerceWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookEcommerceWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112160926_AddBaseproperties")]
    partial class AddBaseproperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookEcommerceWeb.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9242),
                            DisplayOrder = 1,
                            Name = "Hành động",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9243)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9245),
                            DisplayOrder = 2,
                            Name = "Khoa học viễn tưởng",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9245)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9247),
                            DisplayOrder = 3,
                            Name = "Lịch sử",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9247)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9248),
                            DisplayOrder = 4,
                            Name = "Ngôn tình",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9249)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9250),
                            DisplayOrder = 5,
                            Name = "Trinh thám",
                            UpdatedDate = new DateTime(2025, 1, 12, 16, 9, 26, 163, DateTimeKind.Utc).AddTicks(9250)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
